image: mambaorg/micromamba:alpine

cache:
  paths:
    - $MAMBA_ROOT_PREFIX

pages:
  before_script:
    - micromamba create -y -n jupyterlite python=3.13 pip
    - micromamba run -n jupyterlite pip install .
  script:
    - micromamba run -n jupyterlite jupyter lite build --base-url $CI_PAGES_URL
  artifacts:
    paths:
      - public
